### ISSUE TITLE
ENH Allow caller to set bytehash in buzhash

### ISSUE THREAD

**Issue by kshedden** [chmduquesne/rollinghash#4]
I need to be able to set the bytehash table in buzhash when calling New (to create multiple independent rolling hashes).  It's an easy extension (I created an alternative New called NewWithByteHash).  I can make a PR if you are interested.

**Comment by chmduquesne** [comment]
No problem with that, I will accept a PR if you make one.

However, for the sake of consistency, please name your method NewFromByteArray, in order to reflect the naming scheme adopted with NewFromInt in [rabinkarp32](https://github.com/chmduquesne/rollinghash/blob/master/rabinkarp32/rabinkarp32.go#L31).

FYI in the next version of rollinghash, buzhash will be renamed to buzhash32 and I will add a buzhash64 version.
